# Created with podman-5.6.2
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: playfulchefapp
    io.containers.autoupdate: registry
  name: playfulchefapp
spec:
  containers:
    - image: ghcr.io/playful-chef/playful-chef-api:latest
      name: playfulchefapi
    - image: docker.io/library/caddy:2-alpine
      name: caddy
      ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        - containerPort: 443
          hostPort: 443
          protocol: UDP
      volumeMounts:
        - mountPath: /etc/caddy/Caddyfile
          name: caddyfile
          readOnly: true
        - mountPath: /data
          name: caddy-data-pvc
  volumes:
    - name: caddyfile
      hostPath:
        path: /Users/vklepov/Documents/playful-chef-api/caddy/conf/Caddyfile
        type: File
    - name: caddy-data-pvc
      persistentVolumeClaim:
        claimName: caddy-data
